'use strict';

const path = require('path');

module.exports = app => {
  const exports = {};

  /**
   * egg-view-react-loadable default config
   * @property {String} statsFile - entrypoints file generated by @loadable/webpack-plugin
   * @property {Object} layout - client render template, support compile with custom viewEngine
   */
  exports.reactLoadable = {
    statsFile: path.join(app.baseDir, 'app/ssr/loadable-stats.json'),
    // layout: {
    //   path: path.join(app.baseDir, 'app/view/layout.html'),
    //   viewEngine: 'nunjucks',   // support compile with custom viewEngine
    // },
  };

  return exports;
};
