'use strict';

const path = require('path');

module.exports = app => {
  const exports = {};

  /**
   * egg-view-react-loadable default config
   * @property {String} nodeStatsFile - entrypoints file generated by @loadable/webpack-plugin
   * @property {String} webStatsFile - entrypoints file generated by @loadable/webpack-plugin
   * @property {Object} layout - client render template, support compile with custom viewEngine
   */
  exports.reactLoadable = {
    nodeStatsFile: path.join(app.baseDir, 'app/public/ssr/loadable-stats.json'),
    webStatsFile: path.join(app.baseDir, 'app/public/csr/loadable-stats.json'),
    // template: {
    //   renderSSR: {
    //     renderSSRTemplate: path.join(app.baseDir, 'app/view/renderSSRLayout.html'),
    //     viewEngine: 'nunjucks',
    //   },
    //   renderToStream: {
    //     renderToStreamStartTemplate: path.join(app.baseDir, 'app/view/renderToStreamStartTemplate.html'),
    //     renderToStreamEndTemplate: path.join(app.baseDir, 'app/view/renderToStreamEndTemplate.html'),
    //     viewEngine: 'nunjucks',
    //   },
    // },
  };

  return exports;
};
